#!/bin/sh -e

here=$(cd $(dirname $0); pwd)

if [ -d "$here/.svn" ] 
then
    svn up
fi

make version.ss

./run-bot.ss                                    \
--host irc.freenode.org                         \
--nick rudebot                                  \
--nickserv Rahk6aeMquiG4lai                     \
"$@"
